# Generated by Django 5.1.2 on 2025-01-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('link1', models.TextField(max_length=10)),
                ('link2', models.TextField(max_length=10)),
                ('link3', models.TextField(max_length=10)),
                ('link4', models.TextField(max_length=10)),
                ('link5', models.TextField(max_length=10)),
            ],
        ),
    ]
