# Generated by Django 5.1.2 on 2025-01-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_navigationbar_link6'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCarosel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='logo')),
            ],
        ),
        migrations.DeleteModel(
            name='NavigationBar',
        ),
    ]
