# Generated by Django 5.1.2 on 2025-01-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_imagecarosel_delete_navigationbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='logo')),
                ('description', models.TextField()),
                ('cast', models.TextField()),
                ('show_time', models.JSONField()),
                ('category', models.CharField(choices=[('Hindi', 'Hindi Movie'), ('English', 'English Movie'), ('South', 'South Movie'), ('Animated', 'Animated Movie')], max_length=50)),
            ],
        ),
    ]
