# Generated by Django 5.1.2 on 2025-01-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_moviesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='category',
            field=models.CharField(choices=[('Hindi', 'Hindi Movie'), ('English', 'English Movie'), ('South', 'South Movie'), ('Animated', 'Animated Movie'), ('All', 'All Movies')], max_length=50),
        ),
    ]
