# Generated by Django 5.1.2 on 2025-01-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_moviesmodel_tralerlink_moviebooking_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesmodel',
            name='show_time',
        ),
        migrations.RemoveField(
            model_name='moviesmodel',
            name='tralerlink',
        ),
        migrations.AddField(
            model_name='moviesmodel',
            name='trailer',
            field=models.URLField(default='None'),
        ),
    ]
