# Generated by Django 5.1.2 on 2025-01-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_remove_moviesmodel_show_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesmodel',
            name='date',
            field=models.DateField(default='2025-01-26', db_index=True),
        ),
        migrations.AddField(
            model_name='moviesmodel',
            name='time',
           field=models.TimeField(default='10:00', db_index=True),
        ),
    ]
