# Generated by Django 5.1.2 on 2025-01-26 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_moviesmodel_date_moviesmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
