# Generated by Django 5.1.2 on 2025-01-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0009_alter_moviesmodel_date_alter_moviesmodel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moviesmodel',
            name='time',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='MovieBooking',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
