# Generated by Django 5.1.2 on 2025-01-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0010_remove_profile_user_alter_moviesmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='trailer',
            field=models.TextField(),
        ),
    ]
