# Generated by Django 5.1.2 on 2025-01-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0011_alter_moviesmodel_trailer'),
    ]

    operations = [
    ]
