# Generated by Django 5.1.2 on 2025-01-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0012_auto_20250126_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='moviesmodel',
            name='time',
        ),
    ]
