# Generated by Django 5.1.2 on 2025-01-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0013_remove_moviesmodel_date_remove_moviesmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesmodel',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='moviesmodel',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
