# Generated by Django 5.1.2 on 2025-01-26 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0014_moviesmodel_date_moviesmodel_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='moviesmodel',
            name='time',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('MadhyePradesh', 'MadhyePradesh'), ('Uttar Pradesh', 'Uttar Pradesh')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
