# Generated by Django 5.1.2 on 2025-01-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0015_remove_moviesmodel_date_remove_moviesmodel_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='locality',
        ),
    ]
