# Generated by Django 5.1.2 on 2025-01-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0016_remove_customer_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='trailer',
            field=models.URLField(),
        ),
    ]
