# Generated by Django 5.1.2 on 2025-01-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0017_alter_moviesmodel_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('ticket_id', models.CharField(max_length=10, unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('cinema_hall', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seats', models.PositiveIntegerField(default=1)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
