# Generated by Django 5.1.2 on 2025-01-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0019_alter_movietickets_date_alter_movietickets_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietickets',
            name='date',
            field=models.DateField(default='2025-02-12'),
        ),
        migrations.AlterField(
            model_name='movietickets',
            name='time',
            field=models.TimeField(default='12:00'),
        ),
    ]
