# Generated by Django 5.1.2 on 2025-01-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0020_alter_movietickets_date_alter_movietickets_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietickets',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='movietickets',
            name='time',
            field=models.TimeField(default=''),
        ),
    ]
