# Generated by Django 5.1.2 on 2025-01-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0021_alter_movietickets_date_alter_movietickets_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='partners/')),
                ('description', models.TextField()),
            ],
        ),
    ]
