# Generated by Django 5.1.2 on 2025-02-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0022_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietickets',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
